- tests/testArgumentParser.py
Reorganize the test case such that it doesn't attempt to create reruns inside
DataPath (which is part of obs_test).
> DM-10229: Do not write to upstream repository.

- python/lsst/pipe/base/argumentParser.py
> Log to stdout instead of stderr

- python/lsst/pipe/base/argumentParser.py
I didn't run the test after partially implementing a change on tickets/DM-15158: this fixes the error that I introduced.
> fix typo in format string

- python/lsst/pipe/base/pipelineBuilder.py
- tests/test_pipelineBuilder.py
Also added a unit test for substituteDatatypeNames method.
> Move dictionary parsing to ctrl_mpexec (DM-17067)

- python/lsst/pipe/base/graph.py
- python/lsst/pipe/base/graphBuilder.py
New method returns topologically ordered Quanta together with their
pre-requisites. This is used by new refactored code in ctrl_mpexec.
> Add new method for iterating over QuantumGraph.

- python/lsst/pipe/base/graphBuilder.py
This has been fixed upstream in daf_butler.
> DM-17496: Remove workaround for lack of component datasets in preflight.

- doc/lsst.pipe.base/creating-a-task.rst
> DM-11097: Document required entry points for tasks.

- python/lsst/pipe/base/pipeline.py
We now require a parent storage class for components.
> DM-25447: Change how comparison with registry DatasetType happens

- tests/test_pipelineTask.py
Depends on lsst/daf_butler#378
> DM-26738: Rename abstract_filter to band

- python/lsst/pipe/base/pipeline.py
Add as string formatting for filename paths that allows subsetting
labels when loading a pipeline from disk.
> DM-27066 Enable label subset on load for Pipelines

- tests/test_quantumGraph.py
This change makes it compatible with both master and DM-26407 which is on a separate development branch in other packages, but this will be merged into master.
> DM-26407: Update DimensionUniverse constructor in unit test.

- python/lsst/pipe/base/graphBuilder.py
Depends on lsst/daf_butler#400
> DM-27222: Update deduplicate argument to new form of findFirst

- doc/lsst.pipe.base/creating-a-pipeline.rst
- doc/lsst.pipe.base/index.rst
Add documentation explaining how to create and use Pipeline files.
> DM-27416 Add documentation on Pipelines

- python/lsst/pipe/base/executionButlerBuilder.py
- python/lsst/pipe/base/pipeline.py
> DM-30767: include initOutputs in execution butler creation

- python/lsst/pipe/base/graph/_implDetails.py
- python/lsst/pipe/base/graph/graph.py
- tests/test_quantumGraph.py
> DM-31100 Introduce a cleaner helper module for QuantumGraph

- python/lsst/pipe/base/config.py
- python/lsst/pipe/base/pipeline.py
Related to lsst/daf_butler#546
> DM-30977: Add new log file output dataset type

- doc/lsst.pipe.base/command-line-task-parallel-howto.rst
This is a reapplication of #104 -- that PR was waiting to be rebased so it could be merged so I did it myself.
> fixed OpenBLAS and MKL links

- doc/lsst.pipe.base/creating-a-pipeline.rst
> DM-30787: Add label to reference pipeline section

- python/lsst/pipe/base/graph/quantumNode.py
- python/lsst/pipe/base/pipeline.py
- python/lsst/pipe/base/tests/simpleQGraph.py
Few small improvements to generate better exception messages.
>  DM-25013: Improve error messages (pipe_base)

- doc/changes/DM-32459.feature.md
- python/lsst/pipe/base/graphBuilder.py
> DM-32459: Print query to use for debugging when QG is empty.

- doc/changes/DM-27492.api.md
- doc/changes/DM-28646.feature.rst
- doc/changes/DM-30301.other.rst
- doc/changes/DM-30649.feature.rst
- doc/changes/DM-30702.other.rst
- doc/changes/DM-31583.feature.rst
- doc/lsst.pipe.base/CHANGES.rst
- pyproject.toml
> DM-32843: v23 release notes

- .github/workflows/build.yaml
- README.md
- python/lsst/pipe/__init__.py
- python/lsst/pipe/base/__init__.py
- python/lsst/pipe/base/graph/graph.py
- python/lsst/pipe/base/pipeline.py
- python/lsst/pipe/base/tests/simpleQGraph.py
- requirements.txt
- setup.cfg
- setup.py
- tests/test_dataIdContainer.py
- tests/test_pipelineIR.py
- tests/test_quantumGraph.py
- tests/test_showTasks.py
> DM-33260: Add support for GitHub action to run tests

- doc/changes/DM-33345.misc.rst
- python/lsst/pipe/base/executionButlerBuilder.py
> DM-33345 (v23 Backport): Speed up execution butler creation

- .pre-commit-config.yaml
> DM-33403: Update black in pre-commit to 22.1.0

- doc/changes/DM-33345.misc.rst
- doc/lsst.pipe.base/CHANGES.rst
> DM-33525 (v23): v23.0.1rc2 release notes

- doc/changes/DM-33345.misc.rst
- doc/lsst.pipe.base/CHANGES.rst
> DM-33525: v23.0.1rc2 release notes

- .github/workflows/formatting.yaml
- doc/lsst.pipe.base/PipelineTask_Examples
- doc/lsst.pipe.base/creating-a-pipelinetask.rst
- doc/lsst.pipe.base/index.rst
- examples/PipelineTask_Examples/aperturePipelineTaskV1.py
- examples/PipelineTask_Examples/aperturePipelineTaskV2.py
- examples/PipelineTask_Examples/aperturePipelineTaskV3.py
- examples/PipelineTask_Examples/aperturePipelineTaskV4.py
- examples/PipelineTask_Examples/aperturePipelineTaskV5.py
- examples/PipelineTask_Examples/aperturePipelineTaskV6.py
- examples/PipelineTask_Examples/aperturePipelineTaskV7.py
- examples/PipelineTask_Examples/aperturePipelineTaskV8.py
- examples/PipelineTask_Examples/aperturePipelineTaskV9.py
- examples/PipelineTask_Examples/apertureTask.py
- examples/argumentParser.py
Add an initial draft of how-to write a pipeline task. This is
written in markdown because I find it fast to use, but will be
converted (and this commit squashed) before the ticket is close.
> DM-21687: Add draft of how-to PipelineTask

- .github/workflows/formatting.yaml
- .github/workflows/lint.yaml
- .github/workflows/mypy.yaml
- .github/workflows/yamllint.yaml
- types.txt
> switch to reusable workflows

- python/lsst/pipe/base/executionButlerBuilder.py
> DM-33942: Update to support change in export interface

- .github/workflows/build.yaml
- LICENSE
- requirements.txt
- setup.cfg
> DM-35047: Add upload to pypi

- .github/workflows/build.yaml
> DM-35191: Add test matrix for python versions

- .github/workflows/build.yaml
- requirements.txt
> Use build dependencies from github

- doc/lsst.pipe.base/creating-a-pipelinetask.rst
> Replace abstract_filter with band in example pipelines

- .github/workflows/build.yaml
- python/lsst/pipe/base/_dataset_handle.py
- tests/test_dataset_handle.py
> DM-35815: Use StorageClassFactory.findStorageClass

- .github/workflows/build.yaml
- README.md
- doc/changes/DM-31769.feature.rst
- doc/changes/DM-32080.bugfix.rst
- doc/changes/DM-32408.feature.rst
- doc/changes/DM-32459.feature.md
- doc/changes/DM-32682.feature.rst
- doc/changes/DM-33155.feature.rst
- doc/changes/DM-33303.misc.rst
- doc/changes/DM-34105.feature.rst
- doc/changes/DM-34155.misc.rst
- doc/lsst.pipe.base/CHANGES.rst
- pyproject.toml
- python/lsst/pipe/base/config.py
- python/lsst/pipe/base/graph/_versionDeserializers.py
- python/lsst/pipe/base/pipeline.py
- python/lsst/pipe/base/testUtils.py
- python/lsst/pipe/base/tests/no_dimensions.py
- python/lsst/pipe/base/tests/simpleQGraph.py
- ups/pipe_base.table
> DM-36034: v24.0.0 release notes

- README.md
- doc/changes/DM-31769.feature.rst
- doc/changes/DM-32080.bugfix.rst
- doc/changes/DM-32408.feature.rst
- doc/changes/DM-32459.feature.md
- doc/changes/DM-32682.feature.rst
- doc/changes/DM-33155.feature.rst
- doc/changes/DM-33303.misc.rst
- doc/changes/DM-34105.feature.rst
- doc/changes/DM-34155.misc.rst
- doc/lsst.pipe.base/CHANGES.rst
- pyproject.toml
> DM-36034: Add v24.0.0 release notes to main

- doc/changes/DM-36360.misc.md
- python/lsst/pipe/base/graph/_versionDeserializers.py
- python/lsst/pipe/base/graphBuilder.py
> DM-36360: Make empty-QG diagnostics harder to ignore.

- python/lsst/pipe/base/connectionTypes.py
- python/lsst/pipe/base/graphBuilder.py
- python/lsst/pipe/base/tests/simpleQGraph.py
> DM-36313: Adapt to daf_butler dataset type / collection API changes

- .pre-commit-config.yaml
- doc/changes/DM-35681.bugfix.rst
- pyproject.toml
- python/lsst/pipe/base/graph/_loadHelpers.py
- python/lsst/pipe/base/graph/_versionDeserializers.py
- python/lsst/pipe/base/graph/graph.py
- python/lsst/pipe/base/graphBuilder.py
> DM-35681-v24: Pass DimensionUniverse to QuantumGraph at construction

- python/lsst/pipe/base/graphBuilder.py
New logic added on previous ticket tries to resolve intermediate dataset references but it had a bug in handling of component refs.
> DM-37575: Fix handling of component references in GraphBuilder

- python/lsst/pipe/base/graph/_loadHelpers.py
- python/lsst/pipe/base/graph/_versionDeserializers.py
- requirements.txt
- tests/test_quantumGraph.py
> DM-33682 Use ResourcePaths when unpersisting QuantumGraph

- python/lsst/__init__.py
- python/lsst/pipe/__init__.py
- python/lsst/pipe/base/graph/_implDetails.py
> DM-37552: Remove unnecessary lsstimport import

- doc/changes/DM-37786.bugfix.md
- doc/changes/DM-37786.feature.md
- python/lsst/pipe/base/connectionTypes.py
- python/lsst/pipe/base/graphBuilder.py
- python/lsst/pipe/base/pipeline.py
> DM-37786-v25: backport hooks for tasks to set dataset-query-constraint defaults

- doc/changes/DM-37786.bugfix.md
- doc/changes/DM-37786.feature.md
- python/lsst/pipe/base/connectionTypes.py
- python/lsst/pipe/base/graphBuilder.py
- python/lsst/pipe/base/pipeline.py
> DM-37786-v24: backport task control over dataset-query-constraints defaults

- .pre-commit-config.yaml
- doc/changes/DM-35082.feature.rst
- doc/changes/DM-35681.bugfix.rst
- doc/changes/DM-37786.bugfix.md
- doc/changes/DM-37786.feature.md
- doc/lsst.pipe.base/CHANGES.rst
- python/lsst/pipe/base/_task_metadata.py
- python/lsst/pipe/base/connections.py
- python/lsst/pipe/base/graph/_implDetails.py
- python/lsst/pipe/base/graph/_loadHelpers.py
- python/lsst/pipe/base/pipeTools.py
- python/lsst/pipe/base/pipeline.py
- python/lsst/pipe/base/pipelineIR.py
- python/lsst/pipe/base/tests/simpleQGraph.py
- requirements.txt
- setup.cfg
- tests/test_cliCmdRegisterInstrument.py
> DM-38065: V24.1 release notes

- doc/changes/DM-38694.feature.rst
- python/lsst/pipe/base/_dataset_handle.py
- tests/test_dataset_handle.py
> DM-38694: Add support for copying on return with InMemoryDatasetHandle

- python/lsst/pipe/base/connections.py
Needed now that ruff is run automatically by scons.
> DM-38499: Fix noqa code

- python/lsst/pipe/base/_quantumContext.py
> DM-40057: shorten deprecation timeline and add ticket TODOs

- tests/test_pipelineLoadSubset.py
> DM-39849: restore test previously deleted from ci_hsc_gen3

- doc/changes/DM-39779.feature.md
- mypy.ini
- python/lsst/pipe/base/pipeline_graph/__main__.py
- python/lsst/pipe/base/pipeline_graph/_pipeline_graph.py
- python/lsst/pipe/base/pipeline_graph/visualization/__init__.py
- python/lsst/pipe/base/pipeline_graph/visualization/_formatting.py
- python/lsst/pipe/base/pipeline_graph/visualization/_layout.py
- python/lsst/pipe/base/pipeline_graph/visualization/_merge.py
- python/lsst/pipe/base/pipeline_graph/visualization/_options.py
- python/lsst/pipe/base/pipeline_graph/visualization/_printer.py
- python/lsst/pipe/base/pipeline_graph/visualization/_show.py
- tests/test_pipeline_graph.py
> DM-39779: text-based graph visualization of pipelines

- doc/changes/DM-34696.misc.rst
- python/lsst/pipe/base/pipelineTask.py
- python/lsst/pipe/base/struct.py
- python/lsst/pipe/base/tests/no_dimensions.py
- python/lsst/pipe/base/tests/simpleQGraph.py
> DM-34696: Fix some mypy issues in Struct and PipelineTask

- .pre-commit-config.yaml
- python/lsst/pipe/base/all_dimensions_quantum_graph_builder.py
> DM-41761: Updated imports after daf_butler refactoring

- doc/changes/DM-43060.feature.md
- python/lsst/pipe/base/_dataset_handle.py
- python/lsst/pipe/base/caching_limited_butler.py
- tests/test_caching_limited_butler.py
> DM-43060: Write CachingLimitedButler

- doc/changes/DM-43538.bugfix.rst
- tests/test_quantumGraph.py
> DM-43538: Fix metadata packages test.

- .github/workflows/build.yaml
- doc/changes/DM-41542.feature.rst
- python/lsst/pipe/base/graph/__init__.py
- python/lsst/pipe/base/graph/graph.py
- python/lsst/pipe/base/graph/graphSummary.py
- python/lsst/pipe/base/prerequisite_helpers.py
- tests/test_quantumGraph.py
> DM-41542:  Add QuantumGraph summary.

- doc/changes/DM-44341.bugfix.md
- python/lsst/pipe/base/pipeline.py
- python/lsst/pipe/base/tests/mocks/_data_id_match.py
- tests/test_pipeline.py
> DM-44341: Propagate subsetCtrl into subset_from_labels

- doc/changes/DM-44341.bugfix.md
- python/lsst/pipe/base/pipeline.py
- python/lsst/pipe/base/tests/mocks/_data_id_match.py
- tests/test_pipeline.py
> DM-44341-v27: Propagate subsetCtrl into subset_from_labels

- doc/changes/DM-44647.feature.md
- python/lsst/pipe/base/pipeline.py
- python/lsst/pipe/base/pipeline_graph/__main__.py
- python/lsst/pipe/base/pipeline_graph/_dataset_types.py
- python/lsst/pipe/base/pipeline_graph/_edges.py
- python/lsst/pipe/base/pipeline_graph/_nodes.py
- python/lsst/pipe/base/pipeline_graph/_pipeline_graph.py
- python/lsst/pipe/base/pipeline_graph/visualization/__init__.py
- python/lsst/pipe/base/pipeline_graph/visualization/_dot.py
- python/lsst/pipe/base/pipeline_graph/visualization/_formatting.py
- python/lsst/pipe/base/pipeline_graph/visualization/_merge.py
- python/lsst/pipe/base/pipeline_graph/visualization/_show.py
Separate text layout options from the rest.
> DM-44647: Add new show_dot functionality

- .pre-commit-config.yaml
- python/lsst/pipe/base/_task_metadata.py
- python/lsst/pipe/base/tests/no_dimensions.py
> DM-45209: Fix E721 linter warning

- python/lsst/pipe/base/formatters/pexConfig.py
- python/lsst/pipe/base/tests/mocks/_storage_class.py
Depends on lsst/daf_butler#1018
> DM-26658: Use FormatterV2 for configs

- .github/workflows/build.yaml
- doc/changes/DM-45457.feature.md
- pyproject.toml
- python/lsst/pipe/base/connectionTypes.py
- python/lsst/pipe/base/pipeline_graph/_edges.py
- python/lsst/pipe/base/tests/mocks/_pipeline_task.py
- python/lsst/pipe/base/tests/mocks/_storage_class.py
- tests/test_pipeline_graph.py
> DM-45457: Allow optional input connections

- python/lsst/pipe/base/_task_metadata.py
- python/lsst/pipe/base/graph/graphSummary.py
- python/lsst/pipe/base/prerequisite_helpers.py
- python/lsst/pipe/base/tests/mocks/_data_id_match.py
- python/lsst/pipe/base/tests/mocks/_storage_class.py
> DM-45933: minor updates for middleware-internal API changes.

- python/lsst/pipe/base/quantum_graph_builder.py
- python/lsst/pipe/base/tests/mocks/_storage_class.py
- python/lsst/pipe/base/tests/simpleQGraph.py
This has been superseded by 'butler.collections.defaults'.
> DM-46599: Stop using deprecated property butler.collections

- .gitignore
- .pre-commit-config.yaml
- python/lsst/pipe/base/cli/resources.yaml
- tests/SConscript
- ups/pipe_base.table
Now use entry points everywhere for command discovery.
Depends on lsst/sconsUtils#131.
> DM-42226: Remove DAF_BUTLER_PLUGINS support

- doc/changes/DM-47730.feature.md
- python/lsst/pipe/base/_quantumContext.py
- python/lsst/pipe/base/_status.py
- python/lsst/pipe/base/quantum_provenance_graph.py
- tests/test_quantum_success_caveats.py
> DM-47730: add "success caveats" system to report on NoWorkFound and similar cases

- doc/changes/DM-45896.md
- python/lsst/pipe/base/all_dimensions_quantum_graph_builder.py
- python/lsst/pipe/base/prerequisite_helpers.py
- python/lsst/pipe/base/quantum_graph_builder.py
- python/lsst/pipe/base/quantum_graph_skeleton.py
- python/lsst/pipe/base/quantum_provenance_graph.py
- tests/test_graphBuilder.py
> DM-45896: Switch QG builder to new query system

- doc/changes/DM-48536.feature.md
- python/lsst/pipe/base/_status.py
- python/lsst/pipe/base/quantum_provenance_graph.py
- python/lsst/pipe/base/tests/mocks/_pipeline_task.py
- tests/test_quantum_provenance_graph.py
> DM-48536: improvements to QuantumProvenanceGraph

- doc/_static/pipe_base/PipelineTask_Examples/aperturePipelineTaskV1.py
- doc/_static/pipe_base/PipelineTask_Examples/aperturePipelineTaskV2.py
- doc/_static/pipe_base/PipelineTask_Examples/aperturePipelineTaskV3.py
- doc/_static/pipe_base/PipelineTask_Examples/aperturePipelineTaskV4.py
- doc/_static/pipe_base/PipelineTask_Examples/aperturePipelineTaskV5.py
- doc/_static/pipe_base/PipelineTask_Examples/aperturePipelineTaskV6.py
- doc/_static/pipe_base/PipelineTask_Examples/aperturePipelineTaskV7.py
- doc/_static/pipe_base/PipelineTask_Examples/aperturePipelineTaskV8.py
- doc/_static/pipe_base/PipelineTask_Examples/aperturePipelineTaskV9.py
- doc/_static/pipe_base/PipelineTask_Examples/apertureTask.py
- doc/lsst.pipe.base/creating-a-pipelinetask.rst
- doc/lsst.pipe.base/creating-a-task.rst
- doc/lsst.pipe.base/testing-a-pipeline-task.rst
- python/lsst/pipe/base/pipelineTask.py
> DM-49045: run/runQuantum documentation updates from RFC-1052

- doc/changes/DM-48482.feature.rst
- pyproject.toml
- python/lsst/pipe/base/_datasetQueryConstraints.py
- python/lsst/pipe/base/pipeline_graph/visualization/_mermaid.py
> DM-48482: Build image rendering around `mermaid-py` for Mermaid diagrams

- doc/changes/DM-49296.perf.md
- python/lsst/pipe/base/all_dimensions_quantum_graph_builder.py
> DM-49296: optimize QG generation

- doc/changes/DM-49296.perf.md
- python/lsst/pipe/base/all_dimensions_quantum_graph_builder.py
> DM-49296-v29: backport QG generation optimizations and bugfixes

- .github/workflows/build.yaml
- python/lsst/pipe/base/prerequisite_helpers.py
- python/lsst/pipe/base/tests/mocks/_data_id_match.py
- tests/test_graphBuilder.py
Switch to the new bind syntax in query expressions.
> DM-38497: Add visitBind method to expression tree vsitor

- doc/changes/DM-49440.perf.md
- python/lsst/pipe/base/all_dimensions_quantum_graph_builder.py
- python/lsst/pipe/base/quantum_provenance_graph.py
- tests/test_quantum_provenance_graph.py
> DM-49440: Optimizations for QuanutmProvenanceGraph

- doc/changes/DM-35396.feature.rst
- doc/changes/DM-35396.misc.rst
- doc/changes/DM-45896.md
- doc/changes/DM-46023.feature.md
- doc/changes/DM-46503.feature.rst
- doc/changes/DM-46776.feature.rst
- doc/changes/DM-46948.feature.md
- doc/changes/DM-47143.feature.rst
- doc/changes/DM-47328.feature.rst
- doc/changes/DM-47505.misc.md
- doc/changes/DM-47730.feature.md
- doc/changes/DM-48536.feature.md
- doc/changes/DM-49266.bugfix.md
- doc/changes/DM-49296.perf.md
- doc/lsst.pipe.base/CHANGES.rst
- requirements.txt
> DM-49674 (v29): v29 release notes

- .pre-commit-config.yaml
- doc/changes/DM-35396.feature.rst
- doc/changes/DM-35396.misc.rst
- doc/changes/DM-45896.md
- doc/changes/DM-46023.feature.md
- doc/changes/DM-46503.feature.rst
- doc/changes/DM-46776.feature.rst
- doc/changes/DM-46948.feature.md
- doc/changes/DM-47143.feature.rst
- doc/changes/DM-47328.feature.rst
- doc/changes/DM-47505.misc.md
- doc/changes/DM-47730.feature.md
- doc/changes/DM-48536.feature.md
- doc/changes/DM-49266.bugfix.md
- doc/changes/DM-49296.perf.md
- doc/lsst.pipe.base/CHANGES.rst
> DM-49674: v29 release notes

- doc/changes/DM-48913.feature.md
- doc/lsst.pipe.base/working-with-pipeline-graphs.rst
- pyproject.toml
- python/lsst/pipe/base/pipeline_graph/_exceptions.py
- python/lsst/pipe/base/pipeline_graph/_pipeline_graph.py
- python/lsst/pipe/base/pipeline_graph/expressions.py
- tests/test_pipeline_graph.py
- tests/test_pipeline_graph_expressions.py
> DM-48913: add subset expression language to PipelineGraph

- doc/changes/DM-50041.perf.md
- python/lsst/pipe/base/graph/_loadHelpers.py
- python/lsst/pipe/base/graph/graph.py
> DM-50041: Copy QG files to local disk on full reads.

- python/lsst/pipe/base/all_dimensions_quantum_graph_builder.py
- python/lsst/pipe/base/quantum_graph_builder.py
> DM-50310: use daf_butler dimension record attacher instead of local one

- python/lsst/pipe/base/tests/mocks/_data_id_match.py
> DM-50191: Add new TreeVisitor method

- python/lsst/pipe/base/_status.py
- tests/test_task.py
- [NOT RELEVANT] added a release note for user-visible changes to `doc/changes`
> DM-50559: Enforce abc check in AlgorithmError, and test it

- doc/changes/DM-50539.feature.md
- python/lsst/pipe/base/all_dimensions_quantum_graph_builder.py
- python/lsst/pipe/base/connections.py
- python/lsst/pipe/base/quantum_graph_builder.py
- python/lsst/pipe/base/quantum_graph_skeleton.py
- tests/test_adjust_all_quanta.py
> DM-50539: minor QG builder fixes

- python/lsst/pipe/base/caching_limited_butler.py
- tests/test_caching_limited_butler.py
> DM-50491: Add metrics support to CachingLimitedButler

- python/lsst/pipe/base/tests/mocks/_data_id_match.py
> DM-50451: Add new TreeVisitor method

- tests/test_adjust_all_quanta.py
> DM-51363: update how test data from daf_butler is loaded

- .github/workflows/build_docs.yaml
- doc/changes/DM-48206.feature.rst
- doc/changes/DM-48482.feature.rst
- doc/changes/DM-48913.feature.md
- doc/changes/DM-49300.feature.md
- doc/changes/DM-49440.perf.md
- doc/changes/DM-49763.bugfix.md
- doc/changes/DM-49949.feature.md
- doc/changes/DM-50041.perf.md
- doc/changes/DM-50107.bugfix.md
- doc/changes/DM-50539.feature.md
- doc/changes/DM-50885.misc.rst
- doc/changes/DM-50969.bugfix.md
- doc/lsst.pipe.base/CHANGES.rst
- requirements.txt
> DM-51073 (v29.1): v29.1 release notes

- .github/workflows/build_docs.yaml
- doc/changes/DM-48206.feature.rst
- doc/changes/DM-48482.feature.rst
- doc/changes/DM-48913.feature.md
- doc/changes/DM-49300.feature.md
- doc/changes/DM-49440.perf.md
- doc/changes/DM-49763.bugfix.md
- doc/changes/DM-49949.feature.md
- doc/changes/DM-50041.perf.md
- doc/changes/DM-50107.bugfix.md
- doc/changes/DM-50539.feature.md
- doc/changes/DM-50885.misc.rst
- doc/changes/DM-50969.bugfix.md
- doc/lsst.pipe.base/CHANGES.rst
> DM-51073: v29.1 release notes

- .github/workflows/build_docs.yaml
- doc/changes/DM-51176.feature.md
- python/lsst/pipe/base/all_dimensions_quantum_graph_builder.py
- python/lsst/pipe/base/quantum_graph_skeleton.py
- tests/test_qg_builder_dimensions.py
> DM-51176: add healpix support to QG builder

- doc/changes/DM-51509.feature.rst
- python/lsst/pipe/base/connections.py
- python/lsst/pipe/base/prerequisite_helpers.py
- tests/test_adjust_all_quanta.py
> DM-51509: Extend QuantaAdjuster to handle PrerequisiteInputs

- doc/changes/DM-48980.api.md
- doc/lsst.pipe.base/index.rst
- python/lsst/pipe/base/_datasetQueryConstraints.py
- python/lsst/pipe/base/all_dimensions_quantum_graph_builder.py
- python/lsst/pipe/base/connectionTypes.py
- python/lsst/pipe/base/connections.py
- python/lsst/pipe/base/exec_fixup_data_id.py
- python/lsst/pipe/base/execution_graph_fixup.py
- python/lsst/pipe/base/log_capture.py
- python/lsst/pipe/base/mp_graph_executor.py
- python/lsst/pipe/base/quantum_graph_builder.py
- python/lsst/pipe/base/quantum_graph_executor.py
- python/lsst/pipe/base/quantum_reports.py
- python/lsst/pipe/base/separable_pipeline_executor.py
- python/lsst/pipe/base/simple_pipeline_executor.py
- python/lsst/pipe/base/single_quantum_executor.py
- python/lsst/pipe/base/taskFactory.py
- tests/config/datastores/fileDatastore.yaml
- tests/config/storageClasses.yaml
- tests/pipelines/pipeline_separable.yaml
- tests/pipelines/pipeline_simple.yaml
- tests/test_execution_storage_class_conversion.py
- tests/test_executors.py
- tests/test_quantum_reports.py
- tests/test_separable_pipeline_executor.py
- tests/test_simple_pipeline_executor.py
- tests/test_task_factory.py
> DM-48980: transfer pipeline executors and support code from ctrl_mpexec

- python/lsst/pipe/base/dot_tools.py
- python/lsst/pipe/base/graph/graph.py
- python/lsst/pipe/base/mermaid_tools.py
- python/lsst/pipe/base/mp_graph_executor.py
- python/lsst/pipe/base/pipeline_graph/_edges.py
- python/lsst/pipe/base/pipeline_graph/_nodes.py
- python/lsst/pipe/base/pipeline_graph/_tasks.py
- python/lsst/pipe/base/pipeline_graph/visualization/_dot.py
- python/lsst/pipe/base/quantum_graph_builder.py
- python/lsst/pipe/base/quantum_graph_skeleton.py
- python/lsst/pipe/base/quantum_reports.py
- python/lsst/pipe/base/simple_pipeline_executor.py
- python/lsst/pipe/base/single_quantum_executor.py
- python/lsst/pipe/base/tests/mocks/_in_memory_repo.py
- tests/test_dot_tools.py
- tests/test_mermaid.py
> DM-52190: miscellaneous cleanups in preparation for new QG class

- doc/changes/DM-52676.bugfix.rst
- doc/changes/DM-52676.misc.rst
- python/lsst/pipe/base/log_capture.py
- python/lsst/pipe/base/quantum_provenance_graph.py
- python/lsst/pipe/base/tests/mocks/_pipeline_task.py
- python/lsst/pipe/base/tests/simpleQGraph.py
> DM-52676: Fix empty MDC.run in logs.
